
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-13
owner: ucsb-cs156-f25
repo_name: team01-f25-13
pull_requests: [{"author":{"id":"U_kgDOCE2Lig","is_bot":false,"login":"n-ornelas","name":""},"headRefName":"n-ornelas-adjust-README","number":70,"title":"Updated README.md with the correct links and resolved other TODO items","url":"https://github.com/ucsb-cs156-f25/team01-f25-13/pull/70"},{"author":{"id":"U_kgDOCML-cA","is_bot":false,"login":"amyli2027","name":"Amy Li"},"headRefName":"amyli2027---AddPutMenuItemReview","number":69,"title":"Amyli2027   add put menu item review","url":"https://github.com/ucsb-cs156-f25/team01-f25-13/pull/69"},{"author":{"id":"U_kgDOCVyd3Q","is_bot":false,"login":"yulin-Y","name":""},"headRefName":"yy-delete-for-recRquest","number":67,"title":"Yy delete for rec rquest","url":"https://github.com/ucsb-cs156-f25/team01-f25-13/pull/67"},{"author":{"id":"U_kgDOCVyd3Q","is_bot":false,"login":"yulin-Y","name":""},"headRefName":"yy-put-for-recRequest","number":66,"title":"Yy PUT for rec request","url":"https://github.com/ucsb-cs156-f25/team01-f25-13/pull/66"},{"author":{"id":"U_kgDOCVyd3Q","is_bot":false,"login":"yulin-Y","name":""},"headRefName":"yy-recRequest-get-by-id","number":65,"title":"Yy rec request add get by id for recRequest","url":"https://github.com/ucsb-cs156-f25/team01-f25-13/pull/65"},{"author":{"id":"U_kgDOCVyd3Q","is_bot":false,"login":"yulin-Y","name":""},"headRefName":"yy-create-RecRequest-controller","number":64,"title":"Yy create rec request controller, add GET /all and POST method","url":"https://github.com/ucsb-cs156-f25/team01-f25-13/pull/64"},{"author":{"id":"U_kgDOCU6U0g","is_bot":false,"login":"LemoNaCl","name":"Hao Ding"},"headRefName":"hao-create-helpRequest-controller","number":51,"title":"Hao - create help request controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-f25/team01-f25-13/pull/51"},{"author":{"id":"U_kgDOCVyd3Q","is_bot":false,"login":"yulin-Y","name":""},"headRefName":"Yulin-RecRequests","number":47,"title":"yy-create database table for recommendation request","url":"https://github.com/ucsb-cs156-f25/team01-f25-13/pull/47"},{"author":{"id":"U_kgDOCU6U0g","is_bot":false,"login":"LemoNaCl","name":"Hao Ding"},"headRefName":"Hao-HelpRequestTable","number":46,"title":"Hao - create database table for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team01-f25-13/pull/46"}]
